# Generated by Django 5.2.14 on 2026-05-29 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=50)),
                ('universidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Universidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Administracao',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.pessoa')),
                ('nivelAcesso', models.CharField(max_length=20)),
            ],
            bases=('app.pessoa',),
        ),
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=100)),
                ('organizador', models.CharField(max_length=100)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competicoes', to='app.pessoa')),
                ('universidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competicoes', to='app.universidade')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competicoes_gerenciadas', to='app.administracao')),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEvento', models.DateField()),
                ('horario', models.CharField(max_length=20)),
                ('competicao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendario', to='app.competicao')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=200)),
                ('dataEnvio', models.DateField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='app.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(max_length=100)),
                ('colocacao', models.IntegerField()),
                ('pontuacao', models.FloatField()),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='app.competicao')),
            ],
        ),
    ]
