# Generated by Django 5.2.14 on 2026-06-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pesquisa_favorito_historico_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competicao',
            name='descricao',
            field=models.CharField(max_length=1000),
        ),
    ]
